### ISSUE TITLE
HA Core/Container

### ISSUE THREAD

**Issue by guarddog13** [tlskinneriv/hassio-addons#10]
If I want to run the addon in a docker container how could I do that?

**Comment by tlskinneriv** [comment]
You should be able to modify the [Dockerfile](https://github.com/tlskinneriv/hassio-addons/blob/master/awnet/Dockerfile) with the rest of the source in that folder and put together a working container. The awnet.py script will need to be modified with a valid `AUTH_TOKEN` and `url` for publishing the JSON payload value since it will be unable to get that from the supervisor. Using the files as they are is only supported in a Home Assistant supervised installation. I will try to update the files to take some parameters from the command line if I've got some extra time.

**Comment by guarddog13** [comment]
I'm running it with a python script inside a Ubuntu LXC now. Created MQTT sensors in config.yaml on HA. 

One question how did you get the feels like to populate? I know you did the math for solar lx, dew point and feels like but the only sensor of the 3 I need is the feels like....

**Comment by tlskinneriv** [comment]
Take a look at the [method for calculating feels like](https://github.com/tlskinneriv/awnet_local/blob/8fa22d07c3ad02fa5d8b3cf3fd8c8b2113bb1517/custom_components/awnet_local/helpers_calc.py#L71) in the custom integration for source code. The other calculations are there, too, if you want them.

**Comment by guarddog13** [comment]
Thank you i was glancing at that and thinking some template sensors might be in order.

**Comment by tlskinneriv** [comment]
Added some [documentation on the service](https://github.com/tlskinneriv/awnet_local/blob/master/README.md#service) that is made available through the integration. You can call it from python with the HA API and an auth token, and it should be able to send the necessary information through to populate the values for the integration.  Essentially it needs to be passed the mac address as the `PASSKEY` key in the dict, then each sensor value as a member of the dict. Effectively, if you can turn your querystring from the device into the dict object that gets passed to the service, then it should work. Reopen this issue if you've got any other questions.
